### PR TITLE
Better support for dev-* requirements

### LINKED ISSUE #14: dev-* references should update pinned commit in composer.lock
When having a dependency on `dev-master`, the commit hash should be updated in composer.lock if there is a new commit available.

Example: https://app.dependencies.io/projects/github/felixfbecker/vscode-php-intellisense/builds/30

Name | Path | Source | Installed | Found | Actions
-- | -- | -- | -- | -- | --
jetbrains/phpstorm-stubs | / | packagist | `dev-master` | 1 versions | -

### PR DESCRIPTION
**Pull request by davegaeddert**
This is an attempt to fix #14. I'm not sure yet if this is going to work, but my first thought is to include the additional ref information in the same format that you can `composer require`, i.e. `dev-master#sha`. If it is outdated, the latest ref gets prepended to the available list so that it is the first item and they are two distinct items.

The thing I'm not sure about yet though is how this gets used going forward, especially in a dependencies.io config. Currently, it would have to look something like this?
```yml
collectors:
- type: php-composer
  path: /
  actors:
  - type: php-composer
    versions_regex: "#"
```

So the available versions get filtered by the regex, and should have 1 or 0 results. If it has 1 result, that gets passed onto the actor and works like normal. The PR actor would then require it explicitly which would also modify the composer.json...not sure if that's what we'll want exactly or if we'll have to mess with that behavior...

cc @felixfbecker 

Closes #14.

### CODE REVIEW

**Comment by davegaeddert** [comment]
Actually I think in the actor, if this were a transitive dependency it might all work just fine like it is: https://github.com/dependencies-io/actor-php-composer/blob/c9452c9409bd88d0b5d667327f2121e911a0e2c0/entrypoint.php#L56-L59

**Comment by felixfbecker** [comment]
Would this update the `dev-master` reference in composer.json or only in composer.lock?

**Comment by davegaeddert** [comment]
Well, that will be up to the actor. Right now, if it's transitive then it would only update composer.lock. If it's direct then it would update both unless we do something to change that.

**Comment by felixfbecker** [comment]
Got it. The version syntax makes sense to me, but I don't understand why `version_regexp` is needed. Is there no way around that?

**Comment by davegaeddert** [comment]
Yeah I'm not sure yet about that, but I agree it's a little annoying. The problem has to do with how it relates to our [version filtering](https://www.dependencies.io/docs/dependencies-yml/version-filtering/) -- which works great for semver, but not so great for anything else. 

So usually you'd use something like this:
```yml
actors:
- type: php-composer
  versions: L.Y.Y
```
Which, for versions following semver can do a lot of powerful stuff, but it just disregards versions that are not semver. So right now, you'd have to have one actor to deal with everything that follows semver (because it ignores non-semver) and then another actor to deal with the dev-* dependencies if you have and want updates for those:
```yml
actors:
- type: php-composer
  versions: L.Y.Y
- type: php-composer
  versions_regex: "#"  # anything containing "#", which should only be dev- updates
```

That feels a little simpler than the original example I gave, but doing the same thing. For the time being at least, that's probably the way that it's going to go. Right now things are intentionally pretty simple in terms of the JSON schema and everything and I expect that it will be updated if we continue to bump into similar problems across all kinds of languages and kind find good universal ways of dealing with it.

Let me know if you have any other thoughts. I'll give it some more thought too.

**Comment by felixfbecker** [comment]
I was under the impression that the special dependencies would have to be listed out, I guess this fine (but I think the `versions_regex` should be `^dev-`, the hash is not required).
npm allows to install from GitHub repos too by referencing a commit hash, branch, tag, or even a semver range on git tags with `semver:`.

**Comment by davegaeddert** [comment]
The problem with `^dev-` though is that basically every Composer package at least has a `dev-master`, right? And we don't want to match all of those when we're choosing the versions to send to the actor. We just want to send the "update to whatever dev- you're using", which is what our `#` would be telling us.

It's definitely not perfect. It's about the simplest thing I can come up with right now with the rest of the system in mind. Happy to hear other ideas.

I think in most systems you can use different git references, but what's the `semver:` part you're talking about for npm? Is there a special `semver:` prefix you can use on your requirements?

**Comment by felixfbecker** [comment]
Yes, every package has a dev-master. I must have misunderstood the purpose of `version_regex`?

`semver:^5.0.0` would make npm install the highest git tag that looks like a version that matches `^5.0.0`.

**Comment by davegaeddert** [comment]
Yeah so the purpose of the `versions_regex` setting under an actor is to decide which of the available versions that actor will be used on. Similar to `versions` which is the one that is usually used instead and supports semver (i.e. `versions: L.Y.Y` means the actor will be run on minor and patch updates). We have `versions_regex` for everything that is not semver.

Is there a link to that `semver:` syntax? I've never seen that anywhere before.

**Comment by felixfbecker** [comment]
Yes, https://docs.npmjs.com/cli/install

> npm install <git remote url>:
> 
> Installs the package from the hosted git provider, cloning it with git. For a full git remote url, only that URL will be attempted.
> 
>     <protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]
> <protocol> is one of git, git+ssh, git+http, git+https, or git+file.
> 
> If #<commit-ish> is provided, it will be used to clone exactly that commit. If the commit-ish has the format #semver:<semver>, <semver> can be any valid semver range or exact version, and npm will look for any tags or refs matching that range in the remote repository, much as it would for a registry dependency. If neither #<commit-ish> or #semver:<semver> is specified, then master is used.

**Comment by davegaeddert** [comment]
Thanks, I looked there but somehow missed it.

**Comment by davegaeddert** [comment]
I'm going to merge this in. I think we'll have to do a little more work to make sure the user experience is as good as possible, but I feel like that needs to happen in the actor.

**Pull request merged**
